### ISSUE TITLE
sentence2vec请教

### ISSUE THREAD

**Issue by shchsunshine** [siegfang/word2vec#6]
请问你有研究过python格式的sentence2vec吗？我想改为java格式的，但是不知道sentence2vec与word2vec的原理是否一样，希望大神帮忙指点。

**Comment by siegfang** [comment]
与paragraph2vec类同，
论文：http://cs.stanford.edu/~quocle/paragraph_vector.pdf

GitHub地址：https://github.com/klb3713/sentence2vec
